- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 3600 # Harmony: 1 hrs
  startingGear: SecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SecurityOfficerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetSecurity
    pocket1: WeaponDisabler
  storage:
    back:
    - Flash
    # Harmony Change, Remove roundstart Mk-58 and ammo
    #- MagazinePistol
    #- WeaponPistolMk58
    # Harmony End

- type: chameleonOutfit
  id: SecurityOfficerChameleonOutfit
  job: SecurityOfficer
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretSecurity
    mask: ClothingMaskGasSecurity
    neck: Dinkystar
    gloves: ClothingHandsGlovesColorBlack
